### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gentleadam** [pfalcon/micropython-filedb#1]
Hello, 

I'm looking for a simple way to create json config files and update them from the code.
It'd be helpful if your README has some info in it for getting started with this module... it looks cool, I just don't know where to start. 

Thanks!

**Comment by pfalcon** [comment]
Thanks for the feedback.

> I'm looking for a simple way to create json config files and update them from the code.

As hopefully clear from the project name and description, micropython-filedb is a (dumb simple) database, not a config file management system or something.

> It'd be helpful if your README has some info in it for getting started with this module...

Right, it would be nice if someone hired a doc writer to document all things MicroPython...

> it looks cool, I just don't know where to start.

You can either wait for the above, or do what any other programmer does: http://wiki.c2.com/?UseTheSourceLuke

**Comment by gentleadam** [comment]
> Thanks for the feedback.
> 
> > I'm looking for a simple way to create json config files and update them from the code.
> 
> As hopefully clear from the project name and description, micropython-filedb is a (dumb simple) database, not a config file management system or something.
> 
> > It'd be helpful if your README has some info in it for getting started with this module...
> 
> Right, it would be nice if someone hired a doc writer to document all things MicroPython...
> 
> > it looks cool, I just don't know where to start.
> 
> You can either wait for the above, or do what any other programmer does: http://wiki.c2.com/?UseTheSourceLuke

Thanks for your reply. I'm a bit of a beginner to this whole thing, so looking at the code and figuring it out isn't easy. I've spent some time looking through your code, but just can't figure out how to create the DB and add items etc. A little pointer to just creating the DB file and adding a simple item would be appreciated.

Once I have that figured out I'd be happy to contribute some simply documentation.

**Comment by pfalcon** [comment]
> but just can't figure out how to create the DB and add items etc. A little pointer to just creating the DB file and adding a simple item would be appreciated.

Well, but that's why the README here links to https://github.com/pfalcon/picoweb, which in turn links to https://github.com/pfalcon/notes-pico, which has a usage example. Yeah, perhaps it all can be made more direct and explicit, I'll work on that.

> Once I have that figured out I'd be happy to contribute some simply documentation.

Thanks, but I'd recommend to start with reading. If in doubt, read everything ;-).

**Comment by pfalcon** [comment]
Ok, README updated: https://github.com/pfalcon/micropython-filedb/blob/master/README.md

**Comment by gentleadam** [comment]
> > but just can't figure out how to create the DB and add items etc. A little pointer to just creating the DB file and adding a simple item would be appreciated.
> 
> Well, but that's why the README here links to https://github.com/pfalcon/picoweb, which in turn links to https://github.com/pfalcon/notes-pico, which has a usage example. Yeah, perhaps it all can be made more direct and explicit, I'll work on that.
> 
> > Once I have that figured out I'd be happy to contribute some simply documentation.
> 
> Thanks, but I'd recommend to start with reading. If in doubt, read everything ;-).

Thanks, much appreciated! I'll make sure I read as much as possible and figure this out.
